---
- name: Update apt packages.
  become: yes
  apt:
    update_cache: yes
- name: Upgrade packages
  become: yes
  apt:
    upgrade: "yes"
- name: Remove dependencies that are no longer required.
  become: yes
  apt:
    autoremove: "yes"
- name: Install docker dependencies
  become: yes
  apt:
    name: ["tar", "gzip", "git", "apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common", "gnupg2"]
    state: latest
    update_cache: yes
- name: Adding docker official GPG Key
  become: yes
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- name: Install docker stable release
  become: yes
  shell: |
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
- name: Install docker engine.
  become: yes
  apt:
    # name: ["docker-ce", "docker-ce-cli", "containerd.io", "virtualbox", "virtualbox-ext-pack"]
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: latest
    update_cache: yes
- name: Fetch app docker image.
  become: yes
  shell: |
    echo "{{ docker_password }}" | docker login --username {{ docker_user }} --password-stdin
- name: Add ubuntu user to the Docker group.
  become: yes
  shell: |
    # usermod -aG docker $USER && \
    #   newgrp docker
    usermod -aG docker $USER