---
- name: "EC2 backend server configuration for Kubernetes cluster playbook."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - docker_user: "{{ lookup('env', 'DOCKER_USER') }}"
    - docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
    - circle_branch: "{{ lookup('env', 'CIRCLE_BRANCH')}}"

  pre_tasks:
    - name: "wait 2 minutes for docker engine to be reachable/usable."
      wait_for:
        timeout: 120
      delegate_to: localhost
    - name: "install python for Ansible."
      become: true
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  roles:
    - configure-kubernetes