Description: >
  Cloudfront distribution for URL Shortener app.

Parameters:
  WorkflowID:
    Description: Unique pipeline identifier.
    Type: String
  InstanceDNS:
    Description: Backend instance public DNS.
    Type: String

Resources:
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          # - DomainName: !Sub "backend-${WorkflowID}.us-west-2.compute.amazonaws.com"
          - DomainName: !Sub "${InstanceDNS}"
            Id: webpage
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: URL for webapp hosted on an EC2 instance.
    Export:
      Name: WorkflowID
  StaticDNS:
    Value: !GetAtt WebpageCDN.DomainName
    Description: CDN endpoint for webapp.
    Export:
      Name: StaticDNS
