---
- name: Downloading Kubernetes.
  become: yes
  shell: |
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
- name: Fetching Kubernetes binaries checksum.
  become: yes
  shell: |
    echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
- name: Update apt packages.
  become: yes
  apt:
    update_cache: yes
- name: Installing kubectl binaries
  become: yes
  shell: |
    apt-get install -y kubectl
