---
- name: Downloading Kubernetes.
  become: yes
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
- name: Fetching Kubernetes binaries checksum.
  become: yes
  shell: |
    curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
- name: Validating Kubernetes binaries checksum.
  shell: |
    echo "$(<kubectl.sha256) kubectl" | sha256sum --check
- name: Installing kubectl  binaries
  become: yes
  shell: |
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
