---
- name: Fetch app docker image.
  become: yes
  shell: |
    echo "{{ docker_password }}" | docker login --username {{ docker_user }} --password-stdin
- name: Run app.
  become: yes
  shell: |
    docker run -p 80:80 gquiroa/url-shortener:{{ circle_branch }} &